import { Html, Head, Main, NextScript } from "next/document";

export default function Document() {
   return (
      <Html lang="en">
         <Head>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="https://whabtn.vercel.app/favicon.png" />
         </Head>
         <body>
            <Main />
            <NextScript />
         </body>
      </Html>
   );
}
